config/routes.rb
Swiv::Application.routes.draw do

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root :to => "StaticPages#index"

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/seasons/:id/mark_all_seen', to: 'seasons#mark_all_seen', as: 'mark_all_seen_season'

  resources :StaticPages
  resources :users
  resources :shows_users
  resources :episodes_users

  match '/shows/search' => 'shows#search', :as => :show_search
  match 'shows/import'  => 'shows#import(:id)', :as => :show_import
  resources :shows do
    resources :seasons do
      resources :episodes
    end
  end

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessible :air_date, :name, :number, :plot, :season_id, :tvdbid

  validates :tvdbid, presence: true
  validates :name, presence: true

  belongs_to :show, through: :season
  belongs_to :season
  has_and_belongs_to_many :users

  def seen?(user)
    user.episodes.include?(self)
  end

  def mark_seen(user)
    user.episodes << self
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  attr_accessible :number, :show_id

  belongs_to :show
  has_many :episodes

  def all_seen?(user)
    self.episodes.count == user.episodes.select {|ep| ep.season == self }.count
  end

  def mark_all_seen(user)
    episodes.each do |ep|
      ep.mark_seen(user)
    end
  end
end

app/models/show.rb
require 'tvdb'
class Show < ActiveRecord::Base
  attr_accessible :name, :plot, :image, :banner, :tvdbid

  validates :name, presence: true
  validates :tvdbid, presence: true

  has_many :seasons
  has_many :episodes, through: :season
  has_and_belongs_to_many :users

  def self.from_tvdb(tvdb_id)
    TVDB.build_all!(tvdb_id)
  end

  def episodes
    self.seasons.map do |season|
      season.episodes
    end.flatten
  end

end

app/models/shows_users.rb
class ShowsUsers < ActiveRecord::Base
  attr_accessible :show_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  validates :name, presence: true

  has_and_belongs_to_many :shows
  has_and_belongs_to_many :episodes

  def all_seen_ep
    self.shows.map do |show|
      show.episodes.select do |ep|
        ep.seen?(self)
      end
    end.flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
end

app/controllers/episodes_users_controller.rb
class EpisodesUsersController < ApplicationController

  def create
    @episode = Episode.find(params[:episode_id])
    @show = @episode.season.show
    current_user.episodes << @episode

    respond_to do |format|
      format.js   { render 'replace_status.js' }
      format.html { redirect_to(show_path(params[:show_id])) }
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @show = @episode.season.show
    current_user.episodes.delete(@episode)

    respond_to do |format|
      format.js   { render 'replace_status.js' }
      format.html { redirect_to(show_path(params[:show_id])) }
    end
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def mark_all_seen
    @season = Season.find params[:id]
    @season.mark_all_seen current_user

    respond_to do |format|
      format.js   { render 'mark_all.js' }
      format.html { redirect_to show }
    end
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all.sort { |a, b| b.users.count <=> a.users.count }
  end

  def show
    Show.from_tvdb params[:id] unless Show.exists? params[:id]
    @show = Show.find params[:id]
  end

  def search
    terms = params[:search].split(' ').join("%20")
    xml = HTTParty.get("http://www.thetvdb.com/api/GetSeries.php?seriesname=" + terms)

    if xml["Data"].nil?
      redirect_to root_path
      flash[:error] = "No show found!"
    else
      result = xml["Data"]["Series"]
    end

    if result.class == Hash
      @shows = [result]
    else
      @shows = result
    end
  end
end

app/controllers/shows_users_controller.rb
class ShowsUsersController < ApplicationController

  def create
    @show = Show.find params[:show_id]
    current_user.shows << @show

    respond_to do |format|
      format.js   { render 'replace_track.js' }
      format.html { redirect_to(shows_path) }
    end
  end

  def destroy
    @show = Show.find params[:id]
    current_user.shows.delete @show

    respond_to do |format|
      format.js   { render 'replace_track.js' }
      format.html { redirect_to(shows_path) }
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]

    @tracked_shows = @user.shows
    @all_episodes = @user.shows.map(&:episodes).flatten
    @all_seen_episodes = @user.all_seen_ep
    @all_missed_episodes = @all_episodes - @all_seen_episodes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=50"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/episodes/show.html.erb
<h1><%= @episode.name %></h1>
air date: <%= @episode.air_date %>

<h2><%= @episode.plot %></h2>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row-fluid">
    <div class="span4">
      Made by
      <%= link_to "Jonathan Pepin", "http://jypepin.com" %>.
    </div>
    <div class="span2 offset6 socialfooter">
      <a href="http://www.twitter.com/Jauny/"><i class="icon-twitter icon-large social"></i></a>
      <a href="http://www.github.com/Jauny"><i class="icon-github icon-large social"></i></a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <%= link_to "Swiv!", root_path, :class => "brand" %>
    <ul class="nav">
      <li class="divider-vertical"></li>
      <li><%= link_to "Shows", shows_path %></li>
    </ul>
    <ul class="nav pull-right">
      <% if user_signed_in? %>
        <li><%= link_to "Hi #{current_user.name} !", user_path(current_user.id) %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swiv</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36477240-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>
<div class="container">

  <%= render 'layouts/header' %>

  <%= render 'layouts/notice' %>

  <%= yield %>

</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/shows/_all_seen.html.erb
<small id="all_seen" class="pull-right">
  <% if season.all_seen?(current_user) %>
    all seen <i class="icon-ok"></i>
  <% else %>
    <%= link_to "see all", mark_all_seen_season_path(season.id), :remote => true %>
  <% end %>
</small>

app/views/shows/_episodes_list.html.erb
<% @show.seasons.each do |season| %>
    <table class="table table-striped table-hover table-condensed" <%= "id=#{season.number}" %>>
      <caption>
        Season <%= season.number %>
        <% if current_user %>
          <%= render :partial => "shows/all_seen", :locals => { season: season } %>
        <% end %>
      </caption>
      <thead>
        <tr>
          <th width="2%">#</th>
          <th width="20%">Title</th>
          <th width="63%">Plot</th>
          <th width="10%">Air time</th>
          <th width="5%">Status</th>
        </tr>
      </thead>
      <tbody>

        <% sorted_episodes = season.episodes.sort { |a,b| b.number <=> a.number } %>
        <% sorted_episodes.each do |ep| %>
          <% if current_user && ep.seen?(current_user) %>
            <tr class="success">
          <% else %>
            <tr>
          <% end %>
            <td><%= ep.number %></td>
            <td><%= ep.name %></td>
            <td><%= ep.plot %></td>
            <td><%= ep.air_date %></td>
            <%= render :partial => 'shows/status_icon', :locals => { ep: ep } %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

app/views/shows/_status_icon.html.erb
<td class="status" id="status_<%= dom_id(ep) %>" style="text-align:center;">
  <% if user_signed_in? && !current_user.episodes.include?(ep) %>
    <%= link_to '<i class="icon-remove"></i>'.html_safe, episodes_users_path(:episode_id => ep.id, :show_id => @show.id),
                                                         :method => :post, :remote => true %>
  <% elsif user_signed_in? && current_user.episodes.include?(ep) %>
    <%= link_to '<i class="icon-ok"></i>'.html_safe, episodes_user_path(:id => ep.id, :show_id => @show.id),
                                                    :method => :delete, :remote => true %>
  <% end %>
</td>

app/views/shows/_track.html.erb
<div id="track_<%= dom_id(show) %>" class="track">
  <% if user_signed_in? && current_user.shows.include?(show) %>
    <%= link_to '<i class="icon-remove"></i> untrack show'.html_safe, shows_user_path(:id => show.id), :method => :delete, :remote => true %>
  <% elsif user_signed_in? && !current_user.shows.include?(show) %>
    <%= link_to '<i class="icon-ok"></i> track show'.html_safe, shows_users_path(:show_id => show.id), :method => :post, :remote => true %>
  <% end %>
</div>

app/views/shows/index.html.erb
<div class="hero-unit">
  <h2>SEE ALL THE SHOWS!</h2>
  <h5>If your show is not here, just 
    <%= link_to "search", root_path %>
    for it, and it will be imported!</h5>

  <ul class="thumbnails thumbnails-shows">

    <% @shows.each do |show| %>
      <li class="span2 thumbnails">
        
        <%= image_tag show.image ? show.image : "http://lorempixel.com/170/250/" %>
        <%= link_to show.name, show_path(show.id) %>
        <br>

        <%= render partial: 'track', locals: { show: show } %>

      </li>
    <% end %>

  </ul>
</div>

app/views/shows/search.html.erb
<div class="hero-unit">
  <h2>FIND ALL THE SHOWS!</h2>

  <table class="table table-striped table-hover table-condensed">

    <thead>
        <tr>
          <th width="20%">Name</th>
          <th width="80%">Overview</th>
        </tr>
      </thead>

      <tbody>
        <% @shows.each do |show| %>
          <tr>
            <td><%= link_to show["SeriesName"], show_path(show["id"]) %></td>
            <td><%= show["Overview"] %></td>
          </tr>
        <% end %>

      </tbody>

  </table>
</div>

app/views/shows/show.html.erb
<div class="hero-unit">
  <% if @show.banner %>
    <%= image_tag @show.banner %>
  <% else %>
    <%= image_tag "http://lorempixel.com/600/150/" %>
    <h2><%= @show.name %></h2>
  <% end %>

  <% if current_user %>
    <%= render partial: 'track', locals: { show: @show } %>
  <% end %>

  <section id="tabs">
    <ul class="nav nav-tabs" id="seasons-tabs">
      <% @show.seasons.each do |season| %>
        <li>
          <a href=<%= "##{season.number}" %>>Season <%= season.number %></a>
        </li>
      <% end %>
    </ul>

    <%= render 'episodes_list' %>

  </section>

</div>

app/views/static_pages/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=499533736734875";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/static_pages/index.html.erb
<%= render 'facebook' %>
<div class="hero-unit" id="hero-main">
  


  <h1>Find a show</h1>

  <div id="form-main">
    <%= form_tag show_search_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :id => "textfield-main" %>
      <%= submit_tag "Search", :name => nil, :class => "btn btn-large" %>
    <% end %>
  </div>

  <h5>
    This is a really early version. Please 
    <%= mail_to "jypepin@gmail.com", "send" %> 
    any idea or bugs. Thanks!
  </h5>

  <% if flash[:error] %>
    <div class="alert alert-error">
      <%= flash[:error] %>
    </div>
  <% end %>
  
  <p id="social">
    <div class="fb-like" data-href="http://www.swiv.co" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-action="recommend"></div>
  </p>

</div>

app/views/users/_missed_episodes.html.erb
<h2>
  <%= @all_missed_episodes.count %> Missed episodes
</h2>

<ul>
  <% @tracked_shows.each do |show| %>
    <li>
      <%= link_to show.name, show_path(show) %>
      <ul>
        <% show.episodes.select do |ep| %>
          <% if !ep.seen?(@user) %>
          <li>
            <%= link_to '<i class="icon-remove"></i>'.html_safe + ep.name, episodes_users_path(:episode_id => ep.id, :show_id => show.id), :method => :post, :remote => true %>
          </li>
          <% end %>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/users/_tracked_shows.html.erb
<ul class="thumbnails">

  <% @tracked_shows.each do |show| %>
    <li class="span2">
      <%= image_tag show.image %><br>
      <%= link_to show.name, show_path(show.id) %>
    </li>
  <% end %>
  
</ul>

app/views/users/show.html.erb
<div class="hero-unit">
  <h2>
    <%= image_tag avatar_url(@user) %> 
    <%= @user.name %>
    <% if @user == current_user %>
      <%= link_to "(edit)", edit_user_registration_path %>
    <% end %>
  </h2>

  <section id="tabs">
    <ul class="nav nav-tabs" id="user_profile_tabs">
      <li><a href="#episodes">Episodes</a></li>
      <li><a href="#shows">Shows</a></li>
    </ul>
  </section>

  <section id="divs">
    <div id="episodes">
      <h2>
        <%= @user.episodes.count == 0 ? "0 episode" : pluralize(@user.episodes.count, "episode") %> seen.
      </h2>

      <%= render :partial => 'missed_episodes' %>

    </div>

    <div id="shows">
      <h2>
        <%= @user.shows.count == 0 ? "0 show" : pluralize(@user.shows.count, "show") %> tracked.
      </h2>
      <%= render :partial => 'tracked_shows' %>
    </div>
  </section>

</div>